package ru.igorek.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.igorek.addressbook.appmanager.GroupData;
import ru.igorek.addressbook.model.TestBase;

public class createNewGroup extends TestBase {

    @Test
    public void testCreateGropus() {

        app.getGroupHelper().chooseGroups();
        app.getGroupHelper().chooseNewGroup();
        app.getGroupHelper().fillGroup(new GroupData("222", null, null));
        app.getGroupHelper().submitGroup();

        app.getSessionHelper().logOut();
    }

}

