package ru.igorek.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.igorek.addressbook.model.testbase;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class deleteGroup extends testbase {


  @Test
  public void deleteGroup() {

    app.getGroupHelper().chooseGroups();
    app.getGroupHelper().deleteSelectedGroups();
  }

}
