package ru.igorek.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.igorek.addressbook.model.GroupData;
import ru.igorek.addressbook.model.TestBase;

import java.util.Comparator;
import java.util.HashSet;
import java.util.List;

public class groupADD extends TestBase {

    @Test
    public void testCreateGropus() {

        app.getGroupHelper().chooseGroups();
        //int before = app.getGroupHelper().countGroups();
        List<GroupData> before = app.getGroupHelper().getGroupList();
        app.getGroupHelper().chooseNewGroup();
        app.getGroupHelper().fillGroup(new GroupData("222", null, null));
        app.getGroupHelper().submitGroup();
        app.getGroupHelper().chooseGroups();
        List<GroupData> after = app.getGroupHelper().getGroupList();


        Assert.assertEquals(after.size(), before.size() + 1);

        int maxID = 0;
        for (GroupData l : after){
            if (l.getId() > maxID){
                maxID = l.getId();
            }
        }
        int max = after.stream()
                .max(Comparator.comparingInt(GroupData::getId))
                .get()
                .getId();

        before.add(new GroupData(max,"222", null, null));
        Assert.assertEquals(new HashSet<Object>(before),new HashSet<Object>(after));


        //int after = app.getGroupHelper().countGroups();
        app.getSessionHelper().logOut();
    }

}

