package ru.igorek.addressbook.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import ru.igorek.addressbook.model.GroupData;
import ru.igorek.addressbook.model.TestBase;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class groupDELETE extends TestBase {


  @Test
  public void deleteGroup() {

    app.getGroupHelper().chooseGroups();

    if(! app.getGroupHelper().chekGroupExistance()){
      app.getGroupHelper().createGroup(new GroupData("222", null, null));
      app.getGroupHelper().chooseGroups();
    }
    int before = app.getGroupHelper().countGroups();

    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().chooseGroups();

    int after = app.getGroupHelper().countGroups();
    Assert.assertEquals(after, before -1);


  }

}
