package ru.igorek.addressbook.tests;// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Test;
import ru.igorek.addressbook.model.GroupData;
import ru.igorek.addressbook.model.TestBase;

public class groupADD extends TestBase {

    @Test
    public void testCreateGropus() {

        app.getGroupHelper().chooseGroups();
        int before = app.getGroupHelper().countGroups();
        app.getGroupHelper().chooseNewGroup();
        app.getGroupHelper().fillGroup(new GroupData("222", null, null));
        app.getGroupHelper().submitGroup();
        app.getGroupHelper().chooseGroups();

        int after = app.getGroupHelper().countGroups();
        Assert.assertEquals(after, before + 1);
        app.getSessionHelper().logOut();
    }

}

