package ru.igorek.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.igorek.addressbook.model.GroupData;
import ru.igorek.addressbook.model.TestBase;

import java.util.List;

public class groupDELETE extends TestBase {


    @Test
    public void deleteGroup() {

        app.getGroupHelper().chooseGroups();

        if (!app.getGroupHelper().chekGroupExistance()) {
            app.getGroupHelper().createGroup(new GroupData("222", null, null));
            app.getGroupHelper().chooseGroups();
        }

        List<GroupData> before = app.getGroupHelper().getGroupList();
        app.getGroupHelper().chooseGrouptoEdit(0);
        app.getGroupHelper().deleteSelectedGroups();
        app.getGroupHelper().chooseGroups();

        List<GroupData> after = app.getGroupHelper().getGroupList();
        Assert.assertEquals(after.size(), before.size() - 1);

        before.remove(0);
        Assert.assertEquals(after, before);

    }


}
